apiVersion: v1
kind: Service
metadata:
  name: {{ include "sanity-studio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{include "sanity-studio.selectorLabels" . | nindent 4}}
