name: Build Image and Deploy to QA
on:
  pull_request:
    types: [closed]
    branches:
      - Feature_*
    paths-ignore:
      - 'luxedior-chart/*'

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    outputs:
      frontend_digest: ${{ steps.get-digest.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push luxedior-frontend
        id: build-frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            kapil4457/luxedior-frontend:${{ github.sha }}
            kapil4457/luxedior-frontend:latest
          build-args: |
            SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }}  
            SANITY_API_TOKEN=${{ secrets.SANITY_API_TOKEN }}  
            SANITY_API_VERSION=${{ secrets.SANITY_API_VERSION }}  
            SANITY_PROJECT_ENV=${{ secrets.SANITY_PROJECT_ENV }}  
            CLERK_SECRET_KEY=${{secrets.CLERK_SECRET_KEY}}
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
          
      - name: Get frontend image digest
        id: get-digest
        run: |
          echo "digest=${{ steps.build-frontend.outputs.digest }}" >> $GITHUB_OUTPUT
  
  
  
  
  
  
  
  build-and-push-sanity-studio:
    runs-on: ubuntu-latest
    outputs:
      sanity_studio_digest: ${{ steps.get-digest.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push luxedior-sanity-studio
        id: build-sanity
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./sanity-studio/Dockerfile
          push: true
          tags: |
            kapil4457/luxedior-sanity-studio:${{ github.sha }}
            kapil4457/luxedior-sanity-studio:latest
      - name: Get sanity-studio image digest
        id: get-digest
        run: |
          echo "digest=${{  steps.build-sanity.outputs.digest }}" >> $GITHUB_OUTPUT
  
  deploy-to-qa:
    needs: [build-and-push-frontend, build-and-push-sanity-studio]
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: qa