name: Build and  Deploy
on:
  pull_request:
    types: [closed]
    branches:
      - Feature_*
    paths-ignore:
      - 'luxedior-chart/*'
jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    outputs:
      frontend_digest: ${{ steps.get-digest.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Create .env file dynamically
        run: |
          cd frontend
          echo "SANITY_API_TOKEN=${{ secrets.SANITY_API_TOKEN }}" >> .env
          echo "SANITY_API_VERSION=${{ secrets.SANITY_API_VERSION }}" >> .env
          echo "SANITY_PROJECT_ENV=${{ secrets.SANITY_PROJECT_ENV }}" >> .env
          echo "SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }}" >> .env

      - name: build and push luxedior-frontend
        id: build-push
        run: |
          cd frontend
          docker build -t kapil4457/luxedior-frontend:${{ github.sha }} .
          docker push kapil4457/luxedior-frontend:${{ github.sha }}
          docker push kapil4457/luxedior-frontend:latest
      - name: Get frontend image digest
        id: get-digest
        run: |
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' kapil4457/luxedior-frontend:${{ github.sha }})
          echo "digest=$digest" >> "$GITHUB_OUTPUT"
  
  build-and-push-sanity-studio:
    runs-on: ubuntu-latest
    outputs:
      sanity_studio_digest: ${{ steps.get-digest.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push luxedior-sanity-studio
        run: |
          cd sanity-studio
          docker build -t kapil4457/luxedior-sanity-studio:${{ github.sha }} .
          docker push kapil4457/luxedior-sanity-studio:${{ github.sha }}
          docker tag kapil4457/luxedior-sanity-studio:${{ github.sha }} kapil4457/luxedior-sanity-studio:latest
          docker push kapil4457/luxedior-sanity-studio:latest
          
      - name: Get sanity-studio image digest
        id: get-digest
        run: |
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' kapil4457/luxedior-sanity-studio:${{ github.sha }})
          echo "digest=$digest" >> "$GITHUB_OUTPUT"
  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: [build-and-push-frontend, build-and-push-sanity-studio]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Update k8s manifest
        run: |
          cd luxedior-chart
          sed -i "s|kapil4457/luxedior-frontend:.*|kapil4457/luxedior-frontend:${{ needs.build-and-push-frontend.outputs.frontend_digest }}|g" values.yaml
          sed -i "s|kapil4457/luxedior-sanity-studio:.*|kapil4457/luxedior-sanity-studio:${{ needs.build-and-push-sanity-studio.outputs.sanity_studio_digest }}|g" values.yaml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          
          git add luxedior-chart/values.yaml
          git commit -m "Update Kubernetes manifest with new image digests"
          git push origin HEAD:${{ github.ref }}
