name: Deploy to UAT

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - 'luxedior-chart/*'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: uat
