name: Deploy Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        type: choice
        options:
          - qa
          - uat
          - production
        required: true
        default: qa
      frontend_digest:
        description: 'Frontend image digest'
        required: true
        type: string
      sanity_studio_digest:
        description: 'Sanity Studio image digest'
        required: true
        type: string

permissions:
  contents: write

jobs:
  update-k8s-manifest:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Update k8s manifest
        run: |
          cd luxedior-chart
          
          yq e -i '.frontend.image.digest = "'${{ inputs.frontend_digest }}'"' values-${{ inputs.environment }}.yaml
          yq e -i '.studio.image.digest = "'${{ inputs.sanity_studio_digest }}'"' values-${{ inputs.environment }}.yaml


          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git add values-${{ inputs.environment }}.yaml
          git commit --allow-empty -m "Update Kubernetes manifest with new image digests"
          git push origin HEAD:${{ github.ref }}

