apiVersion: v2
name: luxedior
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: frontend
    version: "0.1.0"
    repository: "file://./charts/frontend"
    condition: frontend.enabled
  - name: studio
    version: "0.1.0"
    repository: "file://./charts/sanity-studio"
    condition: studio.enabled
